### ISSUE TITLE
When changing attribute to association, name is forgotten

### ISSUE THREAD

**Issue by jakubklimek** [Dominik7131/Conceptual-Modeling-LLM-Assistant#10]
![change-to-associ](https://github.com/Dominik7131/Conceptual-Modeling-LLM-Assistant/assets/718827/289a956f-7ef8-4fca-845b-4a1bc53ba44c)

**Comment by Dominik7131** [comment]
When converting an attribute to an association the name of the attribute is put into the target class of the association.

For example, if a person has an attribute called "address" and we want to transform this attribute into an association then it makes sense to create the new association like this:
- source class: person
- target class: address

And the new association name is up to the user.

**Comment by jakubklimek** [comment]
Yes, that is indeed what is happening. However, I am not sure if that is desirable. I could imagine that the name is copied both to the class and the assoication name, as the user can change it if it does not fit, but somtimes it does fit, and in those cases, it saves some effort.
