### ISSUE TITLE
Association description suggestion seems like for a class

### ISSUE THREAD

**Issue by martinnec** [Dominik7131/Conceptual-Modeling-LLM-Assistant#3]
For the attached domain description and the model in the attached export.json

[export.json](https://github.com/Dominik7131/Conceptual-Modeling-LLM-Assistant/files/15298436/export.json)
[domain-description-01.txt](https://github.com/Dominik7131/Conceptual-Modeling-LLM-Assistant/files/15298438/domain-description-01.txt)

the suggested description for the association "Purchase game" between classes "player" and "game" is: 

"A player is an individual entity who participates in games, having a unique username, avatar, email address, and password. Players can be part of various teams, and for each game they play, their statistics are tracked, including the number of played sessions, highest achieved score, and best ranking. Players can earn achievements based on their overall gaming performance and have other players as friends. They can enroll in tournaments, which may have entry requirements such as minimum player rankings or fees. Players can purchase games, in-game items, or subscribe to premium memberships, with each transaction linked to the corresponding item. Some tournaments are exclusively available to premium members. Players can rate games with a star rating and review text.:

This seems more like a description of class "player". Maybe some problem in the asociation description suggestion function?

**Comment by Dominik7131** [comment]
Yes, the issue was that the prompt template wasn't correctly filled in and it looked like this:
```
Solely based on the given context provide description for the association: "" of the class: "player" and output it in this JSON object:
{"description": ""}.
```
